package com.amaya.intelligence.impl.ide.antigravity

object AntigravityProtocol {
    object StepTypes {
        const val READ_FILE = "CORTEX_STEP_TYPE_READ_FILE"
        const val WRITE_FILE = "CORTEX_STEP_TYPE_WRITE_FILE"
        const val EDIT_FILE = "CORTEX_STEP_TYPE_EDIT_FILE"
        const val RUN_COMMAND = "CORTEX_STEP_TYPE_RUN_COMMAND"
        const val SEARCH = "CORTEX_STEP_TYPE_SEARCH"
        const val VIEW_FILE = "CORTEX_STEP_TYPE_VIEW_FILE"
        const val VIEW_CODE_ITEM = "CORTEX_STEP_TYPE_VIEW_CODE_ITEM"
        const val VIEW_FILE_OUTLINE = "CORTEX_STEP_TYPE_VIEW_FILE_OUTLINE"
        const val LIST_DIRECTORY = "CORTEX_STEP_TYPE_LIST_DIRECTORY"
        const val GREP_SEARCH = "CORTEX_STEP_TYPE_GREP_SEARCH"
        const val FIND_BY_NAME = "CORTEX_STEP_TYPE_FIND_BY_NAME"
        const val CODE_ACTION = "CORTEX_STEP_TYPE_CODE_ACTION"
        const val REPLACE_FILE_CONTENT = "CORTEX_STEP_TYPE_REPLACE_FILE_CONTENT"
        const val MULTI_REPLACE_FILE_CONTENT = "CORTEX_STEP_TYPE_MULTI_REPLACE_FILE_CONTENT"
        const val GENERATE_IMAGE = "CORTEX_STEP_TYPE_GENERATE_IMAGE"
        const val BROWSER_SUBAGENT = "CORTEX_STEP_TYPE_BROWSER_SUBAGENT"
        const val TASK_BOUNDARY = "CORTEX_STEP_TYPE_TASK_BOUNDARY"
        const val NOTIFY_USER = "CORTEX_STEP_TYPE_NOTIFY_USER"
        const val USER_INPUT = "CORTEX_STEP_TYPE_USER_INPUT"
        const val PLANNER_RESPONSE = "CORTEX_STEP_TYPE_PLANNER_RESPONSE"
        const val CONVERSATION_HISTORY = "CORTEX_STEP_TYPE_CONVERSATION_HISTORY"
        const val KNOWLEDGE_ARTIFACTS = "CORTEX_STEP_TYPE_KNOWLEDGE_ARTIFACTS"
        const val EPHEMERAL_MESSAGE = "CORTEX_STEP_TYPE_EPHEMERAL_MESSAGE"
        const val CHECKPOINT = "CORTEX_STEP_TYPE_CHECKPOINT"
    }

    object ToolMarkers {
        const val THINKING_TOOL_NAME = "thinking"
        const val THINKING_TOOL_META_KEY = "syntheticThinking"
    }
}